#!/usr/bin/env python

import os, sys
import json
import requests

DEBUG = bool(int(os.environ.get('DEBUG', 0) or os.environ.get('HANDLE_EVENT_DEBUG', 0)))
channel = os.environ.get('HANDLE_EVENT_SLACK_CHANNEL')
freq = int(os.environ.get('HANDLE_EVENT_FREQ', 50))
webhook = os.environ['HANDLE_EVENT_SLACK_WEBHOOK']
event_type_filters = [ et.strip().lower() for et in os.environ.get('HANDLE_EVENT_TYPES', 'warning').split(',') ] or ['*']
event = json.loads(os.environ.get('object'))

event_type = event['type'].lower()

if event_type_filters[0] != '*' and event_type not in event_type_filters:
    sys.exit(0)

def post(event, channel=None):
    payload = {
        'username': event['reason'],
        'text': 'Seen {count} times in {namespace}/{name}'.format(
                count=event['count'],
                namespace=event['involvedObject']['namespace'],
                name=event['involvedObject']['name']),
        'attachments': [
            {
                #"title": "App hangs on reboot",
                #"title_link": "http://domain.com/ticket/123456",
                'text': event['message'],
            }
        ]
    }

    if channel:
        payload['channel'] = channel

    return requests.post(url=webhook, headers={'content-type':'application/json'}, data=json.dumps(payload))

count = event['count']
reason = event['reason']

if DEBUG:
    print(json.dumps(event, indent=3))

if count % freq == 0:
    print('Message sent to slack: {reason} x{count} {kind} {namespace}/{name}/{uid}: {message}'.format(
        reason=event['reason'],
        count=event['count'],
        kind=event['involvedObject'].get('kind'),
        namespace=event['involvedObject'].get('namespace'),
        name=event['involvedObject'].get('name'),
        uid=event['involvedObject'].get('uid'),
        message=event['message']))
    post(event, channel).text
